Repository Gosrock/DuDoong-Backend, pull requests merged in 2023-03, with the labels that each got.

#504 docs : 리드미 초안 작성
  .github/workflows/dev-merged-test-coverage.yml
  README.md
Labels: Type: Docs/Chore

#505 feature : health check api
  DuDoong-Api/src/main/java/band/gosrock/api/config/security/SecurityConfig.java
  DuDoong-Api/src/main/java/band/gosrock/api/example/controller/ExampleController.java
  README.md
Labels: For: API, Type: Feature

#506 Api-v1.0.1
  .github/workflows/dev-merged-test-coverage.yml
  DuDoong-Api/src/main/java/band/gosrock/api/config/security/SecurityConfig.java
  DuDoong-Api/src/main/java/band/gosrock/api/example/controller/ExampleController.java
  README.md
Labels: For: API, For: Deploy, Type: Feature

#508 feature : event 거래내역 정산
  DuDoong-Api/src/test/java/band/gosrock/api/email/RegisterUserEventHandlerTest.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementPDF.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSummarySettlement.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventTransactionSettlement.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/adaptor/EventSettlementAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/adaptor/TransactionSettlementAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/domain/EventSettlement.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/repository/EventSettlementRepository.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/repository/TransactionSettlementRepository.java
  DuDoong-Infrastructure/build.gradle
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/PdfRender.java
  DuDoong-Infrastructure/src/main/resources/templates/NanumBarunGothic.ttf
  DuDoong-Infrastructure/src/main/resources/templates/settlement.html
Labels: For: Utils, Type: Feature

#510 feature : 정산서 pdf 생성 , s3 프라이빗 업로드
  DuDoong-Batch/src/main/java/band/gosrock/dto/SettlementPDFDto.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventOrdersToExcel.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementPDF.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSummarySettlement.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/adaptor/EventSettlementAdaptor.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/PdfRender.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/s3/S3PrivateFileUploadService.java
  DuDoong-Infrastructure/src/main/resources/static/images/en-banner-black.png
  DuDoong-Infrastructure/src/main/resources/templates/settlement.html
  README.md
Labels: For: Utils, Type: Feature

#511 feat : 이벤트 정산 내역 이메일 발송 job
  DuDoong-Batch/src/main/java/band/gosrock/job/EventOrdersToExcel.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementEmailToAdmin.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementEmailToHost.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementPDF.java
  DuDoong-Infrastructure/build.gradle
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/s3/S3PrivateFileService.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/ses/AwsSesUtils.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/ses/RawEmailAttachmentDto.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/ses/SendRawEmailDto.java
  DuDoong-Infrastructure/src/main/resources/templates/eventSettlement.html
Labels: For: Utils, Type: Feature

#514 fix : 배치어플레이션 웹서버 세팅 끄기
  DuDoong-Batch/build.gradle
  DuDoong-Batch/src/main/resources/application.yml
  DuDoong-Infrastructure/build.gradle
  DuDoong-Infrastructure/src/main/resources/application-infrastructure.yml
Labels: Type: Docs/Chore

#515 Batch-v1.0.0-1
  DuDoong-Batch/build.gradle
  DuDoong-Batch/src/main/resources/application.yml
  DuDoong-Infrastructure/build.gradle
  DuDoong-Infrastructure/src/main/resources/application-infrastructure.yml
Labels: For: Deploy

#517 refactor : pdf image 가져오는 방식 커스텀
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/B64ImgReplacedElementFactory.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/PdfRender.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/s3/S3PrivateFileService.java
  DuDoong-Infrastructure/src/main/resources/templates/settlement.html
Labels: For: Utils

#518 Batch-v1.0.1
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/B64ImgReplacedElementFactory.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/PdfRender.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/s3/S3PrivateFileService.java
  DuDoong-Infrastructure/src/main/resources/templates/settlement.html
Labels: For: Deploy

#520 refactor : 쿠키우선시 해서 인증 과정 수행
  DuDoong-Api/src/main/java/band/gosrock/api/auth/controller/AuthController.java
  DuDoong-Api/src/main/java/band/gosrock/api/auth/service/helper/CookieHelper.java
  DuDoong-Api/src/main/java/band/gosrock/api/config/security/JwtTokenFilter.java
  README.md
Labels: For: API, For: Utils, Type: Refactor

#522 Api-v1.0.2
  DuDoong-Api/src/main/java/band/gosrock/api/auth/controller/AuthController.java
  DuDoong-Api/src/main/java/band/gosrock/api/auth/service/helper/CookieHelper.java
  DuDoong-Api/src/main/java/band/gosrock/api/config/security/JwtTokenFilter.java
  DuDoong-Api/src/test/java/band/gosrock/api/email/RegisterUserEventHandlerTest.java
  DuDoong-Batch/build.gradle
  DuDoong-Batch/src/main/java/band/gosrock/dto/SettlementPDFDto.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventOrdersToExcel.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementEmailToAdmin.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementEmailToHost.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementPDF.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSummarySettlement.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventTransactionSettlement.java
  DuDoong-Batch/src/main/resources/application.yml
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/adaptor/EventSettlementAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/adaptor/TransactionSettlementAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/domain/EventSettlement.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/repository/EventSettlementRepository.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/settlement/repository/TransactionSettlementRepository.java
  DuDoong-Infrastructure/build.gradle
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/B64ImgReplacedElementFactory.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/pdf/PdfRender.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/s3/S3PrivateFileService.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/s3/S3PrivateFileUploadService.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/ses/AwsSesUtils.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/ses/RawEmailAttachmentDto.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/ses/SendRawEmailDto.java
  DuDoong-Infrastructure/src/main/resources/application-infrastructure.yml
  DuDoong-Infrastructure/src/main/resources/static/images/en-banner-black.png
  DuDoong-Infrastructure/src/main/resources/templates/NanumBarunGothic.ttf
  DuDoong-Infrastructure/src/main/resources/templates/eventSettlement.html
  DuDoong-Infrastructure/src/main/resources/templates/settlement.html
  README.md
Labels: For: Deploy

#521 feat : 이벤트 만료 시 자동 만료 배치 작업 추가
  DuDoong-Batch/src/main/java/band/gosrock/job/EventExpiration.java
  DuDoong-Batch/src/main/java/band/gosrock/job/SlackUserStatistic.java
  DuDoong-Batch/src/main/java/band/gosrock/parameter/DateTimeJobParameter.java
  DuDoong-Batch/src/main/java/band/gosrock/slack/SlackEventExpirationSender.java
  DuDoong-Batch/src/main/java/band/gosrock/slack/SlackUserNotificationSender.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/adaptor/EventAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepository.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/service/EventService.java
  README.md
Labels: For: API, For: Utils, Type: Feature

#525 Api-v1.0.2-1
  DuDoong-Api/src/main/java/band/gosrock/api/ticketItem/dto/response/TicketItemResponse.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventExpiration.java
  DuDoong-Batch/src/main/java/band/gosrock/job/SlackUserStatistic.java
  DuDoong-Batch/src/main/java/band/gosrock/parameter/DateTimeJobParameter.java
  DuDoong-Batch/src/main/java/band/gosrock/slack/SlackEventExpirationSender.java
  DuDoong-Batch/src/main/java/band/gosrock/slack/SlackUserNotificationSender.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/adaptor/EventAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepository.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/service/EventService.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
  README.md
Labels: For: Deploy

#526 Batch-v1.0.2
  DuDoong-Api/src/main/java/band/gosrock/api/auth/controller/AuthController.java
  DuDoong-Api/src/main/java/band/gosrock/api/auth/service/helper/CookieHelper.java
  DuDoong-Api/src/main/java/band/gosrock/api/config/security/JwtTokenFilter.java
  DuDoong-Api/src/main/java/band/gosrock/api/ticketItem/dto/response/TicketItemResponse.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventExpiration.java
  DuDoong-Batch/src/main/java/band/gosrock/job/SlackUserStatistic.java
  DuDoong-Batch/src/main/java/band/gosrock/parameter/DateTimeJobParameter.java
  DuDoong-Batch/src/main/java/band/gosrock/slack/SlackEventExpirationSender.java
  DuDoong-Batch/src/main/java/band/gosrock/slack/SlackUserNotificationSender.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/adaptor/EventAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepository.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/service/EventService.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/ticket_item/domain/TicketItem.java
  README.md
Labels: For: Deploy

#528 fix : 공연 조회 기획 변경 반영
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
Labels: For: API, Type: Errors/Bugs, Type: Refactor

#530 Api-v1.0.2-2
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
Labels: For: Deploy

#532 fix : 준비중인 이벤트 노출 오류 수정
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
Labels: For: API, Type: Errors/Bugs

#533 Api-v1.0.2-3
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
Labels: For: Deploy

#537 feat : 스프링 배치 정산서 전송 안내 알림톡
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendDoneOrderAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendRegisterAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendWithdrawOrderAlimTalkService.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementAlimTalkToHost.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/common/alarm/SettlementKakaoTalkAlarm.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/alilmTalk/NcpHelper.java
Labels: For: Utils

#536 fix : 준비중인 공연 자동 만료 해제
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/cart/domain/CartValidator.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/adaptor/EventAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/domain/Event.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/exception/EventErrorCode.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/exception/EventOpenTimeExpiredException.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepository.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/service/EventService.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/domain/validator/OrderValidator.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/cart/domain/CartValidatorTest.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/event/EventTest.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/order/domain/validator/OrderValidatorTest.java
  README.md
Labels: For: API, Type: Errors/Bugs, Type: Refactor

#538 Batch-v1.0.3
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendDoneOrderAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendRegisterAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendWithdrawOrderAlimTalkService.java
  DuDoong-Batch/src/main/java/band/gosrock/job/EventSettlementAlimTalkToHost.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/common/alarm/SettlementKakaoTalkAlarm.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/cart/domain/CartValidator.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/adaptor/EventAdaptor.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/domain/Event.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/exception/EventErrorCode.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/exception/EventOpenTimeExpiredException.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepository.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/service/EventService.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/domain/validator/OrderValidator.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/cart/domain/CartValidatorTest.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/event/EventTest.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/order/domain/validator/OrderValidatorTest.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/alilmTalk/NcpHelper.java
  README.md
Labels: For: Deploy

#539 refactor : rate limit whitelist ( next js init 대응 )
  DuDoong-Api/src/main/java/band/gosrock/api/config/rateLimit/ThrottlingInterceptor.java
  DuDoong-Api/src/main/resources/application.yml
  DuDoong-Batch/src/main/resources/application.yml
  DuDoong-Domain/src/main/java/band/gosrock/domain/common/aop/redissonLock/RedissonLockAop.java
Labels: For: API, For: Utils, Type: Refactor

#542 feat : 주문 완료 알림톡 버튼 추가
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendDoneOrderAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendWithdrawOrderAlimTalkService.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/common/alarm/OrderKakaoTalkAlarm.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/alilmTalk/NcpHelper.java
Labels: For: Utils

#543 Api-v1.0.2-5
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendDoneOrderAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendWithdrawOrderAlimTalkService.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/common/alarm/OrderKakaoTalkAlarm.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/alilmTalk/NcpHelper.java
Labels: For: Deploy

#545 refactor : event 관리자 주문 철회 권한 올바르게 설정
  DuDoong-Api/src/main/java/band/gosrock/api/order/controller/OrderAdminController.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/controller/OrderController.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/service/CancelOrderUseCase.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/service/WithdrawOrderService.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/order/service/WithdrawOrderServiceTest.java
Labels: For: API, Type: Refactor

#546 Api-v1.0.3
  DuDoong-Api/src/main/java/band/gosrock/api/order/controller/OrderAdminController.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/controller/OrderController.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/service/CancelOrderUseCase.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/service/WithdrawOrderService.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/order/service/WithdrawOrderServiceTest.java
Labels: For: Deploy

#549 refactor : 티켓 스태이지 지난 공연 상태 처리
  DuDoong-Api/src/main/java/band/gosrock/api/order/model/dto/response/OrderBriefElement.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/domain/Event.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/domain/IssuedTickets.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/domain/IssuedTicketsStage.java
Labels: For: API, Type: Refactor

#550 Api-v1.0.3-1
  DuDoong-Api/src/main/java/band/gosrock/api/order/model/dto/response/OrderBriefElement.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/domain/Event.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/domain/IssuedTickets.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/domain/IssuedTicketsStage.java
Labels: For: Deploy

#552 refactor : 배치 어플리케이션 타임존 세팅
  DuDoong-Batch/Dockerfile
  README.md
Labels: For: Deploy, For: Utils

#553 Batch-v1.0.4
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendDoneOrderAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/alimTalk/service/SendWithdrawOrderAlimTalkService.java
  DuDoong-Api/src/main/java/band/gosrock/api/config/rateLimit/ThrottlingInterceptor.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/controller/OrderAdminController.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/controller/OrderController.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/model/dto/response/OrderBriefElement.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/service/CancelOrderUseCase.java
  DuDoong-Api/src/main/resources/application.yml
  DuDoong-Batch/Dockerfile
  DuDoong-Batch/src/main/resources/application.yml
  DuDoong-Domain/src/main/java/band/gosrock/domain/common/alarm/OrderKakaoTalkAlarm.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/common/aop/redissonLock/RedissonLockAop.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/domain/Event.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/domain/IssuedTickets.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/issuedTicket/domain/IssuedTicketsStage.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/service/WithdrawOrderService.java
  DuDoong-Domain/src/test/java/band/gosrock/domain/domains/order/service/WithdrawOrderServiceTest.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/config/alilmTalk/NcpHelper.java
  README.md
Labels: For: Deploy
