Repository Gosrock/DuDoong-Backend, pull requests merged in 2023-07, with the labels that each got.

#562 refactor : 정산서,정산서 이메일 포맷 수정
  DuDoong-Infrastructure/src/main/resources/templates/eventSettlement.html
  DuDoong-Infrastructure/src/main/resources/templates/settlement.html
Labels: For: Markup/UX

#563 Batch-v1.0.5
  DuDoong-Api/src/main/java/band/gosrock/api/order/controller/OrderAdminController.java
  DuDoong-Api/src/main/java/band/gosrock/api/order/service/RefuseOrderUseCase.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/domain/Order.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/domain/validator/OrderValidator.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/exception/CanNotRefuseOrderException.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/exception/OrderErrorCode.java
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/order/service/WithdrawOrderService.java
  DuDoong-Infrastructure/src/main/resources/templates/eventSettlement.html
  DuDoong-Infrastructure/src/main/resources/templates/settlement.html
Labels: For: Deploy

#564 feat : 주문취소 feign retryer bean 추가
  DuDoong-Common/src/main/java/band/gosrock/common/annotation/Phone.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/outer/api/tossPayments/client/PaymentsCancelClient.java
  DuDoong-Infrastructure/src/main/java/band/gosrock/infrastructure/outer/api/tossPayments/config/PaymentCancelErrorDecoder.java
  DuDoong-Infrastructure/src/test/java/band/gosrock/infrastructure/outer/api/tossPayments/client/PaymentsCancelClientTest.java
Labels: For: API

#568 Api-v1.0.6
  DuDoong-Domain/src/main/java/band/gosrock/domain/domains/event/repository/EventCustomRepositoryImpl.java
Labels: For: Deploy
